name:                haskell-scratch
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/haskell-scratch#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web

default-extensions:
  - DataKinds
  - MultiParamTypeClasses
  - GADTs
  - KindSignatures
  - TypeFamilies
  - TypeOperators
  - FlexibleInstances
  - FlexibleContexts
  - PolyKinds
  - TypeApplications
  - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - array
  - vector
  - unordered-containers
  - containers
  - text
  - bytestring
  - hspec
  - QuickCheck
  - zlib
  - hlibgit2
  - gitlib
  - optparse-applicative
  - optparse-text
  - process
  - process-extras

executables:
  haskell-scratch:
    source-dirs:      src
    main:             Main.hs
